version: '3'

services:
  bluesky:
    build:
      context: .
      dockerfile: images/bluesky/Containerfile
      args:
        BASE_IMAGE: ghcr.io/xraygui/nbs-pods/bluesky:latest
    image: rsoxs-bluesky:latest

  queueserver:
    build:
      context: .
      dockerfile: images/queueserver/Containerfile
      args:
        BASE_IMAGE: rsoxs-bluesky:latest
    image: rsoxs-queueserver:latest
    depends_on:
      - bluesky

  gui:
    build:
      context: .
      dockerfile: images/gui/Containerfile
      args:
        BASE_IMAGE: rsoxs-bluesky:latest
    image: rsoxs-gui:latest
    depends_on:
      - bluesky

  sim:
    build:
      context: .
      dockerfile: images/sim/Containerfile
      args:
        BASE_IMAGE: rsoxs-bluesky:latest
    image: rsoxs-sim:latest
    depends_on:
      - bluesky
